// A page finds this release's vendor/ on jsDelivr by version, since import.meta.url may name a bundle

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(new URL('../', import.meta.url)));
const OUTPUT = path.join(ROOT, 'src', 'version.generated.ts');

const { version, dependencies } = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const generated = `// Generated by scripts/embed-version.mjs from package.json. Do not edit.
export const PACKAGE_VERSION: string = ${JSON.stringify(version)};
// The Pyodide a Python snippet runs under, from the CDN unless the page says where
export const PYODIDE_VERSION: string = ${JSON.stringify(dependencies.pyodide)};
`;

// Rewriting identical bytes still moves mtime, which vitest watches
if (!fs.existsSync(OUTPUT) || fs.readFileSync(OUTPUT, 'utf8') !== generated) {
  fs.writeFileSync(OUTPUT, generated);
}
