// Embeds runtime.ts as a string, since a bundle does not keep the file beside the host

import fs from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(new URL('../', import.meta.url)));
const SOURCE = path.join(ROOT, 'src', 'lambda', 'process-runtime.ts');
const OUTPUT = path.join(ROOT, 'src', 'lambda', 'process-runtime.generated.ts');

// Build-time only, so the experimental warning is noise
process.removeAllListeners('warning');
const runtime = stripTypeScriptTypes(fs.readFileSync(SOURCE, 'utf8'));
const generated = `// Generated by scripts/embed-runtime.mjs from process-runtime.ts. Do not edit.
export const PROCESS_RUNTIME_SOURCE: string = ${JSON.stringify(runtime)};
`;

// Rewriting identical bytes still moves mtime, which vitest watches
if (!fs.existsSync(OUTPUT) || fs.readFileSync(OUTPUT, 'utf8') !== generated) {
  fs.writeFileSync(OUTPUT, generated);
}
