// Writes src/python.generated.ts from python/, src/runner/python.generated.ts from
// python/runner/, and src/lambda/python-runtime.generated.ts from python/lambda/, so the
// sources ship inside the JS: a page would otherwise fetch them, and some hosts cannot resolve
// import.meta.url. Run by build, check and test, since vitest reads src/ directly.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Executed in this order into one namespace: threads.py must land before helpers.py imports
// the emulator, and lambda.py patches the emulator's service
const FILES = ['threads.py', 'helpers.py', 'lambda.py'];

const ROOT = path.resolve(fileURLToPath(new URL('../', import.meta.url)));
const SOURCE_DIRECTORY = path.join(ROOT, 'python');
const OUTPUT = path.join(ROOT, 'src', 'python.generated.ts');
const RUNNER_SOURCE = path.join(SOURCE_DIRECTORY, 'runner', 'snippet.py');
const RUNNER_OUTPUT = path.join(ROOT, 'src', 'runner', 'python.generated.ts');
const LAMBDA_SOURCE = path.join(SOURCE_DIRECTORY, 'lambda', 'runtime.py');
const LAMBDA_OUTPUT = path.join(ROOT, 'src', 'lambda', 'python-runtime.generated.ts');

const found = fs.readdirSync(SOURCE_DIRECTORY).filter((file) => file.endsWith('.py'));
const missing = found.filter((file) => !FILES.includes(file));
if (missing.length > 0) {
  process.stderr.write(`[embed-python] ${missing.join(', ')} is not in FILES: add it in run order\n`);
  process.exit(1);
}

const sources = FILES.map((file) =>
  JSON.stringify(fs.readFileSync(path.join(SOURCE_DIRECTORY, file), 'utf8')),
);
const generated = `// Generated by scripts/embed-python.mjs from python/. Do not edit.
export const PYTHON_SOURCES: readonly string[] = [
${sources.map((source) => `  ${source},`).join('\n')}
];
`;

const runner = `// Generated by scripts/embed-python.mjs from python/runner/snippet.py. Do not edit.
export const SNIPPET_PYTHON: string = ${JSON.stringify(fs.readFileSync(RUNNER_SOURCE, 'utf8'))};
`;

const lambda = `// Generated by scripts/embed-python.mjs from python/lambda/runtime.py. Do not edit.
export const PYTHON_RUNTIME_SOURCE: string = ${JSON.stringify(fs.readFileSync(LAMBDA_SOURCE, 'utf8'))};
`;

// Rewriting identical bytes still moves mtime, which vitest watches
for (const [target, content] of [[OUTPUT, generated], [RUNNER_OUTPUT, runner], [LAMBDA_OUTPUT, lambda]]) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) {
    fs.writeFileSync(target, content);
  }
}
