// Writes the src/**/*.generated.ts modules, so what a page would otherwise fetch ships inside the
// JS: some hosts cannot resolve import.meta.url, and a bundle does not keep a file beside it. Run
// by build, check and test, since vitest reads src/ directly.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { rolldown } from 'rolldown';

const ROOT = path.resolve(fileURLToPath(new URL('../', import.meta.url)));
const SRC = path.join(ROOT, 'src');
const PYTHON = path.join(ROOT, 'python');

// Rewriting identical bytes still moves mtime, which vitest watches
function write(target, from, body) {
  const content = `// Generated by scripts/embed.mjs from ${from}. Do not edit.\n${body}`;
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) {
    fs.writeFileSync(target, content);
  }
}

const stringConstant = (name, value) => `export const ${name}: string = ${JSON.stringify(value)};\n`;
const readPython = (file) => fs.readFileSync(path.join(PYTHON, file), 'utf8');

// Executed in this order into one namespace: threads.py must land before helpers.py imports
// the emulator, and lambda.py patches the emulator's service
const REGION_PYTHON = ['threads.py', 'helpers.py', 'lambda.py'];

const missing = fs.readdirSync(path.join(PYTHON, 'region')).filter((file) => file.endsWith('.py') && !REGION_PYTHON.includes(file));
if (missing.length > 0) {
  process.stderr.write(`[embed] ${missing.join(', ')} is not in REGION_PYTHON: add it in run order\n`);
  process.exit(1);
}

write(
  path.join(SRC, 'python.generated.ts'),
  'python/region/',
  `export const PYTHON_SOURCES: readonly string[] = [
${REGION_PYTHON.map((file) => `  ${JSON.stringify(readPython(`region/${file}`))},`).join('\n')}
];
`,
);
// Each runs as one string in an interpreter of its own, so the shared bridge goes in front
const BRIDGE = 'common/boto3_bridge.py';
const bridged = (file) => `${readPython(BRIDGE)}\n\n${readPython(file)}`;
write(
  path.join(SRC, 'runner', 'python.generated.ts'),
  `python/${BRIDGE} and python/runner/snippet.py`,
  stringConstant('SNIPPET_PYTHON', bridged('runner/snippet.py')),
);
write(
  path.join(SRC, 'lambda', 'python-runtime.generated.ts'),
  `python/${BRIDGE} and python/lambda/runtime.py`,
  stringConstant('PYTHON_RUNTIME_SOURCE', bridged('lambda/runtime.py')),
);

// A page finds this release's vendor/ on jsDelivr by version, since import.meta.url may name a bundle
const { version } = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
write(path.join(SRC, 'version.generated.ts'), 'package.json', stringConstant('PACKAGE_VERSION', version));

async function bundle(options, generate = {}) {
  const build = await rolldown({ logLevel: 'warn', ...options });
  const { output } = await build.generate({ format: 'esm', ...generate });
  await build.close();
  return output;
}

// Each Lambda runtime as one module. A Node child imports Node's own modules from its install; a
// worker from a Blob URL can import nothing
const RUNTIMES = [
  ['process-runtime', 'PROCESS_RUNTIME_SOURCE', 'node', [/^node:/]],
  ['worker-runtime', 'WORKER_RUNTIME_SOURCE', 'browser', []],
];
for (const [name, constant, platform, external] of RUNTIMES) {
  const source = `${name}.ts`;
  const chunks = await bundle({ input: path.join(SRC, 'lambda', source), platform, external });
  if (chunks.length !== 1) throw new Error(`${source} bundled into ${chunks.length} chunks, not one`);
  // Rolldown only warns about an import it cannot bundle, and keeps it
  const unbundled = chunks[0].imports.filter((specifier) => !external.some((allowed) => allowed.test(specifier)));
  if (unbundled.length > 0) throw new Error(`${source} still imports ${unbundled.join(', ')}, which its runtime cannot load`);
  write(path.join(SRC, 'lambda', `${name}.generated.ts`), source, stringConstant(constant, chunks[0].code));
}

// Sucrase with no imports: jsDelivr's +esm build of it fails to load in a browser
const sucrase = JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules', 'sucrase', 'package.json'), 'utf8'));
const [transform] = await bundle(
  {
    input: 'entry',
    platform: 'browser',
    plugins: [
      {
        name: 'entry',
        resolveId: (id) => (id === 'entry' ? id : null),
        load: (id) => (id === 'entry' ? "export { transform } from 'sucrase';" : null),
      },
    ],
  },
  { minify: true },
);
write(
  path.join(SRC, 'runner', 'sucrase.generated.ts'),
  `sucrase ${sucrase.version} (MIT, github.com/alangpierce/sucrase)`,
  `// @ts-nocheck\n${transform.code}`,
);
