// Bundles Sucrase into one module with no imports: jsDelivr's +esm build of it fails to load in a browser

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { rolldown } from 'rolldown';

const ROOT = path.resolve(fileURLToPath(new URL('../', import.meta.url)));
const OUTPUT = path.join(ROOT, 'src', 'runner', 'sucrase.generated.ts');

const { version } = JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules', 'sucrase', 'package.json'), 'utf8'));
const bundle = await rolldown({
  input: 'entry',
  platform: 'browser',
  logLevel: 'warn',
  plugins: [
    {
      name: 'entry',
      resolveId: (id) => (id === 'entry' ? id : null),
      load: (id) => (id === 'entry' ? "export { transform } from 'sucrase';" : null),
    },
  ],
});
const { output } = await bundle.generate({ format: 'esm', minify: true });
await bundle.close();

const generated = `// Generated by scripts/embed-sucrase.mjs from sucrase ${version} (MIT, github.com/alangpierce/sucrase). Do not edit.
// @ts-nocheck
${output[0].code}`;

// Rewriting identical bytes still moves mtime, which vitest watches
if (!fs.existsSync(OUTPUT) || fs.readFileSync(OUTPUT, 'utf8') !== generated) {
  fs.writeFileSync(OUTPUT, generated);
}
