// Bundles each runtime into one module and embeds it as a string, since a bundle does not keep
// the file beside the host

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { rolldown } from 'rolldown';

const ROOT = path.resolve(fileURLToPath(new URL('../', import.meta.url)));
const LAMBDA = path.join(ROOT, 'src', 'lambda');
const RUNTIMES = [
  ['process-runtime.ts', 'process-runtime.generated.ts', 'PROCESS_RUNTIME_SOURCE', 'node'],
  ['worker-runtime.ts', 'worker-runtime.generated.ts', 'WORKER_RUNTIME_SOURCE', 'browser'],
];

// A Node child imports Node's own modules from its install; a worker from a Blob URL can import nothing
const NODE_BUILTIN = /^node:/;

for (const [source, output, name, platform] of RUNTIMES) {
  const external = platform === 'node' ? [NODE_BUILTIN] : [];
  const bundle = await rolldown({ input: path.join(LAMBDA, source), platform, external, logLevel: 'warn' });
  const { output: chunks } = await bundle.generate({ format: 'esm' });
  await bundle.close();
  if (chunks.length !== 1) throw new Error(`${source} bundled into ${chunks.length} chunks, not one`);
  // Rolldown only warns about an import it cannot bundle, and keeps it
  const unbundled = chunks[0].imports.filter((specifier) => !external.some((allowed) => allowed.test(specifier)));
  if (unbundled.length > 0) throw new Error(`${source} still imports ${unbundled.join(', ')}, which its runtime cannot load`);

  const generated = `// Generated by scripts/embed-runtime.mjs from ${source}. Do not edit.
export const ${name}: string = ${JSON.stringify(chunks[0].code)};
`;
  const target = path.join(LAMBDA, output);
  // Rewriting identical bytes still moves mtime, which vitest watches
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== generated) {
    fs.writeFileSync(target, generated);
  }
}
